name: depth-on-demand
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - pytorch3d
dependencies:
  - python=3.10.11
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - torchdata=0.6.0
  - lightning=2.0.3
  - albumentations=1.3.1
  - kornia=0.6.12
  - pytorch3d=0.7.4

  # dev
  - ipython
  - ipykernel
  - black
  - pytest

  # c++ dependencies
  - eigen

  - pip
  - pip:
    - pipe==2.0.0
    - omegaconf==2.3.0
    - open3d==0.17.0
    - plyfile==0.9.0
    - pykitti==0.3.1
    - timm==0.9.7
    - viser>=0.1.7<1.0.0
    - h5py>=3.10.0
    - git+https://github.com/PoseLib/PoseLib.git
    - git+https://github.com/cvg/LightGlue.git
    - gdown

