args:
  root: data/tartanair
  batch_size: 1
  load_prevs: 0
  shuffle_keyframes: false
  order_sources_by_pose: false
  keyframes: standard
  min_depth: 0.001
  max_depth: 100.0

inference:
  depth_hints:
    interval: 5
    density: 500
    hints_from_pcd: false
    pnp_pose: false
  source:
    interval: 5
  model_eval_params:
    n_cycles: 10